/*
 * ENOSX AI — ImageDisplay
 * Renders assistant-generated images inline in the chat.
 * Supports URLs and base64 data URLs with a lightbox preview.
 */

import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Download, Maximize2, ImageOff, ExternalLink } from "lucide-react";
import { useTheme } from "@/contexts/ThemeContext";

interface ImageDisplayProps {
  src: string;
  alt?: string;
  caption?: string;
  /** Shows ENOSX branding on images generated by the assistant. */
  watermark?: boolean;
}

export default function ImageDisplay({ src, alt = "Generated image", caption, watermark = false }: ImageDisplayProps) {
  const { config } = useTheme();
  const [isExpanded, setIsExpanded] = useState(false);
  const [isLoaded, setIsLoaded] = useState(false);
  const [hasError, setHasError] = useState(false);

  useEffect(() => {
    setIsLoaded(false);
    setHasError(false);
  }, [src]);

  const downloadSource = async (): Promise<string> => {
    if (!watermark) return src;

    try {
      const source = new Image();
      source.crossOrigin = "anonymous";
      source.src = src;
      await new Promise<void>((resolve, reject) => {
        source.onload = () => resolve();
        source.onerror = () => reject(new Error("Generated image is not CORS-enabled"));
      });

      const logo = new Image();
      logo.src = "/enosx-logo.svg";
      await new Promise<void>((resolve, reject) => {
        logo.onload = () => resolve();
        logo.onerror = () => reject(new Error("ENOSX logo failed to load"));
      });

      const canvas = document.createElement("canvas");
      canvas.width = source.naturalWidth;
      canvas.height = source.naturalHeight;
      const context = canvas.getContext("2d");
      if (!context || !canvas.width || !canvas.height) throw new Error("Unable to prepare watermark canvas");

      context.drawImage(source, 0, 0);
      const logoSize = Math.max(48, Math.min(canvas.width, canvas.height) * 0.14);
      const padding = Math.max(12, logoSize * 0.16);
      context.globalAlpha = 0.78;
      context.drawImage(logo, canvas.width - logoSize - padding, canvas.height - logoSize - padding, logoSize, logoSize);
      context.globalAlpha = 1;
      return canvas.toDataURL("image/png");
    } catch {
      // Some remote providers disallow canvas access; the on-screen watermark remains visible.
      return src;
    }
  };

  const handleDownload = async () => {
    try {
      const source = await downloadSource();
      const response = await fetch(source);
      if (!response.ok) throw new Error("Image download failed");
      const blobUrl = URL.createObjectURL(await response.blob());
      const a = document.createElement("a");
      a.href = blobUrl;
      a.download = `enosx-image-${Date.now()}.png`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(blobUrl);
    } catch {
      // Data URLs and providers that disallow CORS can still be opened directly.
      const a = document.createElement("a");
      a.href = src;
      a.target = "_blank";
      a.rel = "noreferrer";
      a.download = `enosx-image-${Date.now()}.png`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
    }
  };

  return (
    <>
      <div className="relative group my-3" style={{ maxWidth: 640 }}>
        {/* Loading shimmer */}
        {!isLoaded && !hasError && (
          <div
            className="absolute inset-0 animate-pulse"
            style={{
              background: "linear-gradient(90deg, rgba(255,255,255,0.05) 25%, rgba(255,255,255,0.1) 50%, rgba(255,255,255,0.05) 75%)",
              backgroundSize: "200% 100%",
              animation: "shimmer 1.5s infinite",
            }}
          />
        )}

        {!hasError && (
          <img
            src={src}
            alt={alt}
            onLoad={() => setIsLoaded(true)}
            onError={() => { setIsLoaded(false); setHasError(true); }}
            className={`w-full max-h-[420px] object-contain transition-all duration-300 cursor-pointer
              ${isLoaded ? "opacity-100" : "opacity-0"}
            `}
            onClick={() => setIsExpanded(true)}
          />
        )}

        {hasError && (
          <div
            role="status"
            className="flex min-h-24 max-w-[420px] items-center gap-3 rounded-xl border px-4 py-3 text-sm"
            style={{
              color: config.text,
              background: "rgba(0,0,0,0.24)",
              borderColor: "rgba(255,255,255,0.12)",
            }}
          >
            <ImageOff size={18} className="shrink-0 opacity-60" aria-hidden="true" />
            <div className="min-w-0">
              <p className="font-medium">Image unavailable</p>
              <p className="mt-0.5 text-xs opacity-60">The source may have expired or been removed.</p>
              {/^https?:\/\//i.test(src) && (
                <a
                  href={src}
                  target="_blank"
                  rel="noreferrer"
                  className="mt-2 inline-flex items-center gap-1 text-xs underline underline-offset-2 opacity-80 hover:opacity-100"
                >
                  Open original image <ExternalLink size={12} aria-hidden="true" />
                </a>
              )}
            </div>
          </div>
        )}

        {watermark && isLoaded && (
          <img
            src="/enosx-logo.svg"
            alt=""
            aria-hidden="true"
            className="pointer-events-none absolute bottom-3 right-3 w-14 rounded-lg opacity-75 drop-shadow-lg"
          />
        )}

        {/* Action overlay */}
        <AnimatePresence>
          {isLoaded && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute top-2 right-2 flex gap-1.5 opacity-0 group-hover:opacity-100 transition-opacity duration-200"
            >
              <button
                onClick={(e) => { e.stopPropagation(); setIsExpanded(true); }}
                className="w-7 h-7 rounded-lg flex items-center justify-center backdrop-blur-sm transition-all duration-150"
                style={{
                  background: "rgba(0,0,0,0.5)",
                  border: "1px solid rgba(255,255,255,0.15)",
                  color: "rgba(255,255,255,0.8)",
                }}
                title="Expand"
              >
                <Maximize2 size={12} />
              </button>
              <button
                onClick={(e) => { e.stopPropagation(); handleDownload(); }}
                className="w-7 h-7 rounded-lg flex items-center justify-center backdrop-blur-sm transition-all duration-150"
                style={{
                  background: "rgba(0,0,0,0.5)",
                  border: "1px solid rgba(255,255,255,0.15)",
                  color: "rgba(255,255,255,0.8)",
                }}
                title="Download"
              >
                <Download size={12} />
              </button>
            </motion.div>
          )}
        </AnimatePresence>

        {caption && (
          <div
            className="mt-1.5 px-1 text-[11px] italic opacity-60"
            style={{ color: config.text }}
          >
            {caption}
          </div>
        )}
      </div>

      {/* Fullscreen lightbox */}
      <AnimatePresence>
        {isExpanded && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="fixed inset-0 z-[100] flex items-center justify-center p-4"
            style={{ background: "rgba(0,0,0,0.85)", backdropFilter: "blur(12px)" }}
            onClick={() => setIsExpanded(false)}
          >
            <div className="relative max-w-[90vw] max-h-[90vh]" onClick={(e) => e.stopPropagation()}>
              <motion.img
                initial={{ scale: 0.85, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0.85, opacity: 0 }}
                transition={{ type: "spring", stiffness: 300, damping: 30 }}
                src={src}
                alt={alt}
                className="max-w-[90vw] max-h-[90vh] object-contain rounded-xl shadow-2xl"
              />
              {watermark && (
                <img
                  src="/enosx-logo.svg"
                  alt=""
                  aria-hidden="true"
                  className="pointer-events-none absolute bottom-4 right-4 w-20 rounded-xl opacity-75 drop-shadow-2xl"
                />
              )}
            </div>
            <motion.button
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.2 }}
              onClick={() => setIsExpanded(false)}
              className="absolute top-4 right-4 w-10 h-10 rounded-full flex items-center justify-center"
              style={{
                background: "rgba(255,255,255,0.1)",
                border: "1px solid rgba(255,255,255,0.2)",
                color: "white",
              }}
            >
              <X size={20} />
            </motion.button>
            <motion.button
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.2 }}
              onClick={(e) => { e.stopPropagation(); handleDownload(); }}
              className="absolute bottom-4 right-4 w-10 h-10 rounded-full flex items-center justify-center"
              style={{
                background: "rgba(255,255,255,0.1)",
                border: "1px solid rgba(255,255,255,0.2)",
                color: "white",
              }}
            >
              <Download size={20} />
            </motion.button>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
