export type ConnectorKind = "Built-in" | "MCP" | "API";

export interface ConnectorCatalogItem {
  id: string;
  name: string;
  kind: ConnectorKind;
}

/**
 * The first 100 services in the current Manus connector inventory snapshot.
 * Only display-safe names and connector kinds are embedded in the client.
 * Credentials, endpoints, and connector UIDs remain outside the frontend.
 */
export const CONNECTOR_CATALOG: ConnectorCatalogItem[] = [
  { id: "connector-001", name: "AWS Knowledge", kind: "MCP" },
  { id: "connector-002", name: "AWeber", kind: "MCP" },
  { id: "connector-003", name: "ActiveCampaign", kind: "MCP" },
  { id: "connector-004", name: "Adzviser", kind: "MCP" },
  { id: "connector-005", name: "Agent Opus", kind: "MCP" },
  { id: "connector-006", name: "AgentMail", kind: "MCP" },
  { id: "connector-007", name: "Ahrefs", kind: "MCP" },
  { id: "connector-008", name: "Ahrefs API", kind: "API" },
  { id: "connector-009", name: "AirOps", kind: "MCP" },
  { id: "connector-010", name: "Airtable", kind: "MCP" },
  { id: "connector-011", name: "AllTrails", kind: "MCP" },
  { id: "connector-012", name: "Alma Food", kind: "MCP" },
  { id: "connector-013", name: "Alpaca", kind: "MCP" },
  { id: "connector-014", name: "Alpha Vantage", kind: "MCP" },
  { id: "connector-015", name: "Amplemarket", kind: "MCP" },
  { id: "connector-016", name: "Amplitude", kind: "MCP" },
  { id: "connector-017", name: "Anchor Browser", kind: "API" },
  { id: "connector-018", name: "Anthropic", kind: "API" },
  { id: "connector-019", name: "Apify", kind: "MCP" },
  { id: "connector-020", name: "Apify", kind: "Built-in" },
  { id: "connector-021", name: "Apollo", kind: "MCP" },
  { id: "connector-022", name: "Apollo API", kind: "API" },
  { id: "connector-023", name: "Asana", kind: "MCP" },
  { id: "connector-024", name: "Atlassian", kind: "MCP" },
  { id: "connector-025", name: "Attio", kind: "MCP" },
  { id: "connector-026", name: "Aurora", kind: "MCP" },
  { id: "connector-027", name: "Ayrshare", kind: "MCP" },
  { id: "connector-028", name: "Base", kind: "MCP" },
  { id: "connector-029", name: "Bigdata.com", kind: "MCP" },
  { id: "connector-030", name: "BioRender", kind: "MCP" },
  { id: "connector-031", name: "Bitly", kind: "MCP" },
  { id: "connector-032", name: "Blockscout", kind: "MCP" },
  { id: "connector-033", name: "Blotato", kind: "MCP" },
  { id: "connector-034", name: "Box", kind: "MCP" },
  { id: "connector-035", name: "Brand24", kind: "MCP" },
  { id: "connector-036", name: "Brandfetch", kind: "MCP" },
  { id: "connector-037", name: "Braze", kind: "MCP" },
  { id: "connector-038", name: "Brex", kind: "MCP" },
  { id: "connector-039", name: "Bright Data", kind: "MCP" },
  { id: "connector-040", name: "Buffer", kind: "MCP" },
  { id: "connector-041", name: "Cafe24", kind: "MCP" },
  { id: "connector-042", name: "Cal.com", kind: "MCP" },
  { id: "connector-043", name: "CalendarBridge", kind: "MCP" },
  { id: "connector-044", name: "Calendly", kind: "MCP" },
  { id: "connector-045", name: "Canva", kind: "MCP" },
  { id: "connector-046", name: "Carta CRM", kind: "MCP" },
  { id: "connector-047", name: "Circleback", kind: "MCP" },
  { id: "connector-048", name: "Clarify", kind: "MCP" },
  { id: "connector-049", name: "Clay", kind: "MCP" },
  { id: "connector-050", name: "Clerk", kind: "MCP" },
  { id: "connector-051", name: "ClickUp", kind: "MCP" },
  { id: "connector-052", name: "Close", kind: "MCP" },
  { id: "connector-053", name: "Cloudflare", kind: "MCP" },
  { id: "connector-054", name: "Cloudflare API", kind: "API" },
  { id: "connector-055", name: "Cloudflare Worker Bindings", kind: "MCP" },
  { id: "connector-056", name: "Cloudinary Asset", kind: "MCP" },
  { id: "connector-057", name: "Clover API", kind: "API" },
  { id: "connector-058", name: "Coda", kind: "MCP" },
  { id: "connector-059", name: "Cohere", kind: "API" },
  { id: "connector-060", name: "CoinDesk", kind: "MCP" },
  { id: "connector-061", name: "CoinGecko", kind: "MCP" },
  { id: "connector-062", name: "CoinMarketCap", kind: "MCP" },
  { id: "connector-063", name: "Comfy Cloud", kind: "MCP" },
  { id: "connector-064", name: "Common Room", kind: "MCP" },
  { id: "connector-065", name: "Consensus", kind: "MCP" },
  { id: "connector-066", name: "Contentsquare", kind: "MCP" },
  { id: "connector-067", name: "Context7", kind: "MCP" },
  { id: "connector-068", name: "Coralogix", kind: "MCP" },
  { id: "connector-069", name: "Craft", kind: "MCP" },
  { id: "connector-070", name: "Crossbeam", kind: "MCP" },
  { id: "connector-071", name: "Crypto.com", kind: "MCP" },
  { id: "connector-072", name: "Customer.io", kind: "MCP" },
  { id: "connector-073", name: "DataFast", kind: "MCP" },
  { id: "connector-074", name: "DataForSEO", kind: "MCP" },
  { id: "connector-075", name: "Databricks", kind: "MCP" },
  { id: "connector-076", name: "Day AI", kind: "MCP" },
  { id: "connector-077", name: "Deel", kind: "MCP" },
  { id: "connector-078", name: "Deepnote", kind: "MCP" },
  { id: "connector-079", name: "Demodesk", kind: "MCP" },
  { id: "connector-080", name: "Descript", kind: "MCP" },
  { id: "connector-081", name: "DevRev", kind: "MCP" },
  { id: "connector-082", name: "Dex", kind: "MCP" },
  { id: "connector-083", name: "Dice", kind: "MCP" },
  { id: "connector-084", name: "Dify", kind: "MCP" },
  { id: "connector-085", name: "Digits", kind: "MCP" },
  { id: "connector-086", name: "Dovetail", kind: "MCP" },
  { id: "connector-087", name: "Dropbox", kind: "MCP" },
  { id: "connector-088", name: "Dropbox API", kind: "API" },
  { id: "connector-089", name: "Dupe", kind: "MCP" },
  { id: "connector-090", name: "Egnyte", kind: "MCP" },
  { id: "connector-091", name: "Elastic Email", kind: "MCP" },
  { id: "connector-092", name: "ElevenLabs", kind: "MCP" },
  { id: "connector-093", name: "ElevenLabs API", kind: "API" },
  { id: "connector-094", name: "Elicit", kind: "MCP" },
  { id: "connector-095", name: "Enterpret", kind: "MCP" },
  { id: "connector-096", name: "Eraser", kind: "MCP" },
  { id: "connector-097", name: "Etsy", kind: "MCP" },
  { id: "connector-098", name: "Exa", kind: "MCP" },
  { id: "connector-099", name: "Excalidraw", kind: "MCP" },
  { id: "connector-100", name: "Explorium", kind: "MCP" },
];
